USE `Spuria`;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DELETE FROM Producto;

DELETE FROM Tienda;
DELETE FROM Patrocinante;
DELETE FROM Consumidor;
DELETE FROM Administrador;

DELETE FROM Continente;
DELETE FROM Subcontinente;
DELETE FROM Pais;
DELETE FROM Estado;
DELETE FROM Ciudad;
DELETE FROM Municipio;
DELETE FROM Parroquia;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;